#!/usr/bin/env python3
"""
Keycloak Deployment Script - Deploys Keycloak + PostgreSQL via Docker Compose.
Generates secure secrets, writes .env, and starts services.
Idempotent: safe to run multiple times.
"""

import argparse
import hashlib
import json
import os
import secrets
import subprocess
import sys
import time


def generate_secret(length=48):
    """Generate a cryptographically secure random password."""
    return secrets.token_urlsafe(length)


def write_env_file(env_path, postgres_password, admin_password):
    """Write .env file with generated secrets."""
    content = f"""# Keycloak Manager - Auto-generated .env file
# Generated by deploy.py - DO NOT commit to version control

# --- PostgreSQL Database Secrets ---
POSTGRES_PASSWORD={postgres_password}

# --- Keycloak Admin Secrets ---
KC_BOOTSTRAP_ADMIN_PASSWORD={admin_password}
"""
    with open(env_path, "w") as f:
        f.write(content)
    os.chmod(env_path, 0o600)  # Owner read/write only
    print(f"[OK] Environment file written: {env_path}")


def check_docker():
    """Verify Docker and Docker Compose are available."""
    try:
        ver = subprocess.run(
            ["docker", "--version"], capture_output=True, text=True, timeout=10
        )
        print(f"[OK] Docker: {ver.stdout.strip()}")
    except Exception as e:
        print(f"[FAIL] Docker not available: {e}", file=sys.stderr)
        return False

    try:
        ver = subprocess.run(
            ["docker", "compose", "version"], capture_output=True, text=True, timeout=10
        )
        print(f"[OK] Docker Compose: {ver.stdout.strip()}")
    except Exception as e:
        print(f"[FAIL] Docker Compose not available: {e}", file=sys.stderr)
        return False

    return True


def check_ports():
    """Check that required ports are available."""
    ports = [8080, 5432, 9000]
    descriptions = {
        8080: "Keycloak HTTP",
        5432: "PostgreSQL",
        9000: "Keycloak Health/Metrics",
    }

    all_ok = True
    for port in ports:
        try:
            import socket
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(2)
            result = sock.connect_ex(("127.0.0.1", port))
            sock.close()
            if result == 0:
                print(f"[WARN] Port {port} ({descriptions[port]}) is already in use")
                all_ok = False
            else:
                print(f"[OK] Port {port} ({descriptions[port]}) is available")
        except Exception:
            pass
    return all_ok


def deploy(compose_dir, fresh=False):
    """Deploy Keycloak using Docker Compose."""
    compose_file = os.path.join(compose_dir, "docker-compose.yml")
    if not os.path.exists(compose_file):
        print(f"[ERROR] docker-compose.yml not found at {compose_file}", file=sys.stderr)
        return False

    # Stop existing containers if fresh deploy
    if fresh:
        print("[INFO] Stopping existing containers...")
        subprocess.run(
            ["docker", "compose", "-f", compose_file, "down", "--remove-orphans"],
            capture_output=True, text=True, timeout=120,
        )

    # Pull latest images
    print("[INFO] Pulling images...")
    result = subprocess.run(
        ["docker", "compose", "-f", compose_file, "pull"],
        capture_output=True, text=True, timeout=300,
    )
    if result.returncode != 0:
        print(f"[ERROR] Failed to pull images: {result.stderr}", file=sys.stderr)
        return False

    # Start services
    print("[INFO] Starting services...")
    result = subprocess.run(
        ["docker", "compose", "-f", compose_file, "up", "-d"],
        capture_output=True, text=True, timeout=300,
    )
    if result.returncode != 0:
        print(f"[ERROR] Failed to start services: {result.stderr}", file=sys.stderr)
        return False

    print("[OK] Services started")
    return True


def wait_for_ready(compose_dir, timeout=300):
    """Wait for Keycloak to be ready."""
    print(f"[INFO] Waiting for Keycloak to be ready (timeout {timeout}s)...")
    start = time.time()

    while time.time() - start < timeout:
        try:
            result = subprocess.run(
                ["docker", "compose", "-f", os.path.join(compose_dir, "docker-compose.yml"), "ps"],
                capture_output=True, text=True, timeout=15,
            )
            output = result.stdout

            # Check both services are running
            if "keycloak-db" in output and "keycloak" in output:
                # Check Keycloak health via port
                import socket
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(2)
                if sock.connect_ex(("127.0.0.1", 8080)) == 0:
                    sock.close()
                    print("[OK] Keycloak is ready!")
                    return True
                sock.close()
        except Exception:
            pass

        time.sleep(5)
        print(".", end="", flush=True)

    print("\n[WARN] Timeout waiting for Keycloak. It may still be starting.")
    return False


def show_status(compose_dir):
    """Show deployment status."""
    result = subprocess.run(
        ["docker", "compose", "-f", os.path.join(compose_dir, "docker-compose.yml"), "ps"],
        capture_output=True, text=True, timeout=15,
    )
    print(result.stdout)


def main():
    parser = argparse.ArgumentParser(description="Deploy Keycloak via Docker Compose")
    parser.add_argument(
        "-d", "--dir", default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        help="Directory containing docker-compose.yml",
    )
    parser.add_argument(
        "--fresh", action="store_true",
        help="Stop existing containers before deploying",
    )
    parser.add_argument(
        "--generate-secrets", action="store_true",
        help="Generate new secrets (WARNING: this invalidates existing admin credentials)",
    )
    parser.add_argument(
        "--status", action="store_true",
        help="Show deployment status",
    )
    parser.add_argument(
        "--stop", action="store_true",
        help="Stop Keycloak services",
    )
    parser.add_argument(
        "--logs", action="store_true",
        help="Show logs",
    )
    parser.add_argument(
        "--recreate", action="store_true",
        help="Recreate containers (stop + deploy)",
    )

    args = parser.parse_args()
    compose_dir = args.dir

    if args.status:
        show_status(compose_dir)
        return

    if args.stop:
        subprocess.run(
            ["docker", "compose", "-f", os.path.join(compose_dir, "docker-compose.yml"), "down"],
            capture_output=True, text=True, timeout=120,
        )
        print("[OK] Services stopped")
        return

    if args.logs:
        subprocess.run(
            ["docker", "compose", "-f", os.path.join(compose_dir, "docker-compose.yml"), "logs", "--tail=50"],
            timeout=30,
        )
        return

    # Check prerequisites
    if not check_docker():
        sys.exit(1)

    check_ports()

    env_path = os.path.join(compose_dir, ".env")

    # Generate secrets if needed
    if args.generate_secrets:
        print("[INFO] Generating secure secrets...")
        postgres_pw = generate_secret()
        admin_pw = generate_secret()
        write_env_file(env_path, postgres_pw, admin_pw)
        print(f"[OK] PostgreSQL password: {postgres_pw}")
        print(f"[OK] Admin password: {admin_pw}")
        print("[WARN] Save these passwords! They cannot be recovered.")
    elif not os.path.exists(env_path):
        print("[INFO] No .env file found. Generating secure secrets...")
        postgres_pw = generate_secret()
        admin_pw = generate_secret()
        write_env_file(env_path, postgres_pw, admin_pw)
        print(f"\n[CRITICAL] Save these passwords immediately:")
        print(f"  PostgreSQL password: {postgres_pw}")
        print(f"  Admin password: {admin_pw}")
        print("[WARN] These cannot be recovered if lost!\n")
    else:
        print(f"[OK] Using existing .env file: {env_path}")

    # Deploy
    if args.recreate:
        deploy(compose_dir, fresh=True)
    else:
        deploy(compose_dir, fresh=args.fresh)

    # Wait for readiness
    wait_for_ready(compose_dir)

    # Show status
    show_status(compose_dir)


if __name__ == "__main__":
    main()
