#!/usr/bin/env python3
"""Exercise a phishing ticket lifecycle without invoking a model.

This verifies the durable platform objects an agent uses: ticket context, notes,
approval gate, workflow, workflow run, postmortem, and audit trail.
"""
import json
import sys
import urllib.error
import urllib.request


BASE = sys.argv[1].rstrip("/") if len(sys.argv) > 1 else "http://localhost:25480"


def request(method, path, body=None):
    data = None
    headers = {}
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(f"{BASE}{path}", data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        print(exc.read().decode("utf-8"), file=sys.stderr)
        raise


def assert_true(value, message):
    if not value:
        raise AssertionError(message)


def main():
    ticket = request("POST", "/api/tickets", {
        "title": "Smoke phishing report with suspicious URL",
        "description": "User reported a message with URL http://example.invalid/login and sender display-name mismatch. This is a safe lifecycle test.",
        "ticket_class": "Incident",
        "priority": "P2",
        "provider": "local",
        "sync_provider": False,
        "created_by": "smoke-test",
    })
    ticket_id = ticket["id"]

    note = request("POST", f"/api/tickets/{ticket_id}/notes", {
        "body": "Parsed headers, extracted URL, identified test indicator, and prepared remediation plan.",
        "author": "smoke-test",
        "source": "workflow-test",
    })
    assert_true(note.get("id"), "ticket note failed")

    attachment = request("POST", f"/api/tickets/{ticket_id}/attachments", {
        "filename": "reported-message.eml",
        "content_type": "message/rfc822",
        "sha256": "0" * 64,
        "metadata": {"source": "smoke-test", "safe": True},
    })
    assert_true(attachment.get("id"), "attachment metadata failed")

    request("POST", "/api/knowledge", {
        "title": "Phishing smoke workflow",
        "body": "For phishing reports, collect recipients, URLs, sender authentication, clicks, and request approval before blocking or deleting messages.",
        "category": "phishing",
        "source": "smoke-test",
        "tags": ["phishing", "approval", "workflow"],
    })

    change = request("POST", "/api/changes/request", {
        "ticket_id": ticket_id,
        "action": "block_url",
        "target": "http://example.invalid/login",
        "reason": "Safe test of approval-gated phishing remediation.",
        "risk_level": "medium",
        "approval_policy": {"requires_approval": True, "environment": "test"},
    })
    change_id = change["change_id"]
    status = request("GET", f"/api/changes/{change_id}/status")
    assert_true(status["status"] == "pending", "change did not wait for approval")
    request("POST", f"/api/changes/{change_id}/approve", {"approved_by": "smoke-test"})
    request("POST", f"/api/changes/{change_id}/complete", {"result": "No production change executed; approval lifecycle verified."})

    workflow = request("POST", "/api/workflows", {
        "name": "phishing-smoke-lifecycle",
        "description": "Reference phishing triage workflow generated by smoke test.",
        "ticket_class": "Incident",
        "trigger_type": "ticket",
        "status": "tested",
        "blueprint": "Collect context, enrich indicators, request approval for remediation, document results, then run postmortem.",
        "test_plan": "Create safe phishing ticket, request approval, complete workflow run, create postmortem.",
        "test_results": "Pending final assertions.",
        "approval_policy": {"destructive_actions_require_approval": True},
        "created_by": "smoke-test",
    })
    workflow_id = workflow["id"]
    run = request("POST", f"/api/workflows/{workflow_id}/runs", {
        "ticket_id": ticket_id,
        "status": "running",
    })
    request("POST", f"/api/workflows/runs/{run['id']}/complete", {
        "status": "completed",
        "result": "Phishing workflow lifecycle completed in safe mode.",
    })

    postmortem = request("POST", "/api/postmortems", {
        "ticket_id": ticket_id,
        "status": "draft",
        "summary": "Safe phishing lifecycle confirmed ticket, note, attachment, approval, workflow, and postmortem primitives.",
        "went_well": "Approval gate blocked remediation until explicit approval.",
        "improvements": "Provider adapters should add real recipient/click telemetry in customer deployments.",
        "workflow_proposal": "Promote phishing-smoke-lifecycle as a reference test workflow.",
        "skill_proposals": [{"name": "phishing-triage-provider-adapter", "purpose": "Normalize mail gateway, SIEM, EDR, and ITSM evidence."}],
        "test_cases": [{"name": "approval required before block", "status": "passed"}],
        "guardrails": ["Never delete mail, block URLs, or quarantine endpoints without a change request."],
        "documentation": "Smoke lifecycle created by script.",
        "created_by": "smoke-test",
    })
    request("POST", f"/api/postmortems/{postmortem['id']}/review", {
        "reviewed_by": "smoke-test",
        "approved": True,
        "review_notes": "Safe lifecycle primitives verified.",
    })

    context = request("GET", f"/api/tickets/{ticket_id}/context")
    assert_true(context.get("ticket", {}).get("id") == ticket_id, "context missing ticket")
    assert_true(context.get("change_requests"), "context missing change")
    assert_true(context.get("postmortems"), "context missing postmortem")
    assert_true(any(w["id"] == workflow_id for w in context.get("workflows", [])), "context missing workflow")

    audit = request("GET", f"/api/dashboard/audit?ticket_id={ticket_id}&limit=100")
    assert_true(audit.get("audit"), "audit trail missing")

    print(json.dumps({
        "status": "ok",
        "ticket_id": ticket_id,
        "change_id": change_id,
        "workflow_id": workflow_id,
        "postmortem_id": postmortem["id"],
        "audit_entries": len(audit["audit"]),
    }, indent=2))


if __name__ == "__main__":
    main()
